# Generated by Django 4.0.2 on 2022-03-01 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='^[0-9]{3,3}$')], verbose_name='код мобильного оператора'),
        ),
    ]
