# Generated by Django 4.0.2 on 2022-03-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mailout_filter_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='creation_time',
            field=models.DateTimeField(auto_created=True, verbose_name='время создания'),
        ),
    ]
