# Generated by Django 4.0.2 on 2022-03-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_message_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('is_planned', 'planned'), ('is_sent', 'sent'), ('cancelled', 'cancelled'), ('error', 'error')], max_length=50, verbose_name='статус отправки'),
        ),
    ]
